# -*- coding: utf-8 -*-

{
    'name': 'Odoo Connector',
    'version': '0.2',
    'category': 'Sales',
    'summary': 'Odoo Common Connector, FTP/SFTP/Shopify/Woocomerce Connector',
    'author': 'Eauto Tech',
    'maintainer': 'Eauto Tech',
    'license': 'OPL-1',
    'support': 'Eauto Tech',
    'website': 'https://eauto-tech.odoo.com',
    'depends': ['delivery', 'sale_stock'],
    'data': [
        'security/security_group.xml',
        'security/ir.model.access.csv',
        'data/process_data.xml',
        'views/connector_instance_view.xml',
        'views/process_config_view.xml',
        'views/process_log_view.xml',
        'views/process_mapper_view.xml',
        'views/process_protocol_view.xml',
        'views/product_instance_view.xml',
        'views/product_tmpl_instance_view.xml',
        'views/connector_menus.xml',
    ],
    'installable': True,
    'application': True,
    'price': 100.00,
    'currency': 'EUR',
    'images': ['static/description/images/connector_base_eat.png'],
    'qweb': [],
    'pre_init_hook': 'create_required_table',
    # 'post_init_hook': 'remove_useless_foreign_key',
}
